// ═══════════════════════════════════════════════════════════════
// ADVENTURES DATA — generated by the Campaign Editor tool.
// Paste this whole file over js/adventures-data.js in the repo.
//
// Editing tips if you tweak this file by hand afterwards:
//  - "tone" must be one of: quest-1 … quest-6
//  - "skill" on each objective must be exactly "Reading", "Writing"
//    or "Social"
//  - The homepage teaser shows the FIRST THREE campaigns in this
//    array — reorder campaigns in the tool to change that.
// ═══════════════════════════════════════════════════════════════

const ADVENTURES = [
  {
    "slug": "lantern-marsh",
    "name": "The Lantern Marsh",
    "tagline": "A soggy mystery with very polite cats",
    "tone": "quest-3",
    "group": "Ages 8–10 · Party of 4",
    "sessions": "Session 6 of 10",
    "blurb": "The marsh lanterns have gone out one by one, and the treefolk of Reedhome need heroes small enough to sneak through the reeds and brave enough to ask the right questions.",
    "world": [
      {
        "session": "Session 1",
        "title": "Arrival at Reedhome",
        "body": "The party met Mayor Bulrush and learned the lanterns keep the mist-things away. They were each given a reed charm."
      },
      {
        "session": "Session 3",
        "title": "The Sunken Library",
        "body": "Under the water sat a library of waterproof books. The heroes read three clues aloud to open the door."
      },
      {
        "session": "Session 5",
        "title": "The Lamplighter's Letter",
        "body": "A half-burnt letter revealed the old lamplighter did not vanish — she is hiding. The party wrote a reply and sent it by heron."
      },
      {
        "session": "Session 6",
        "title": "Into the Deep Reeds",
        "body": "Currently exploring the deep reeds, following heron tracks toward a hidden houseboat."
      }
    ],
    "characters": [
      {
        "name": "Pipwick Marsh",
        "player": "Player A",
        "role": "Halfling Ranger",
        "note": "Keeps a field journal of every animal the party meets."
      },
      {
        "name": "Sir Bramble",
        "player": "Player B",
        "role": "Tortle Paladin",
        "note": "Has sworn an oath to never let a friend go hungry."
      },
      {
        "name": "Nettle",
        "player": "Player C",
        "role": "Goblin Artificer",
        "note": "Built a lantern that only lights when someone tells the truth."
      },
      {
        "name": "Moss",
        "player": "Player D",
        "role": "Frogfolk Bard",
        "note": "Composes a short rhyme at the end of every session."
      }
    ],
    "objectives": [
      {
        "label": "Read a short passage aloud to the group",
        "skill": "Reading",
        "done": true
      },
      {
        "label": "Find key details in a written clue",
        "skill": "Reading",
        "done": true
      },
      {
        "label": "Write an in-character letter",
        "skill": "Writing",
        "done": true
      },
      {
        "label": "Describe a place using three senses",
        "skill": "Writing",
        "done": false
      },
      {
        "label": "Take turns without interrupting",
        "skill": "Social",
        "done": true
      },
      {
        "label": "Negotiate a plan the whole party agrees on",
        "skill": "Social",
        "done": false
      }
    ]
  },
  {
    "slug": "clockwork-caravan",
    "name": "The Clockwork Caravan",
    "tagline": "Inventors, deserts and one very lost robot",
    "tone": "quest-4",
    "group": "Ages 10–12 · Party of 5",
    "sessions": "Session 4 of 8",
    "blurb": "A travelling caravan of tinkerers rolls across the Amber Waste. Its engine is failing, its map is wrong, and the only one who remembers the way is a rusted automaton who speaks in riddles.",
    "world": [
      {
        "session": "Session 1",
        "title": "Hired at Brasswell",
        "body": "The party joined the caravan as guards and were each handed a toolbelt and a job title."
      },
      {
        "session": "Session 2",
        "title": "The Riddle of Cog",
        "body": "Cog the automaton would only answer questions asked politely and precisely. The party wrote their questions down first."
      },
      {
        "session": "Session 4",
        "title": "Sandstorm Council",
        "body": "Currently sheltering from a storm and debating whether to trust the merchant Halba."
      }
    ],
    "characters": [
      {
        "name": "Zia Sparkwrench",
        "player": "Player E",
        "role": "Gnome Inventor",
        "note": "Draws a diagram of every machine she meets."
      },
      {
        "name": "Ordo",
        "player": "Player F",
        "role": "Dragonborn Fighter",
        "note": "Appointed caravan captain by unanimous vote."
      },
      {
        "name": "Little Fen",
        "player": "Player G",
        "role": "Human Scout",
        "note": "Keeps the party's map and updates it each session."
      },
      {
        "name": "Marbleye",
        "player": "Player H",
        "role": "Warforged Cleric",
        "note": "Collects sayings and writes them on their own arm."
      },
      {
        "name": "Tamsin",
        "player": "Player I",
        "role": "Tiefling Rogue",
        "note": "Negotiated the party's pay up by two gold each."
      }
    ],
    "objectives": [
      {
        "label": "Read instructions and follow them in order",
        "skill": "Reading",
        "done": true
      },
      {
        "label": "Skim a document for one specific fact",
        "skill": "Reading",
        "done": true
      },
      {
        "label": "Write clear questions before asking them",
        "skill": "Writing",
        "done": true
      },
      {
        "label": "Keep a written session log",
        "skill": "Writing",
        "done": false
      },
      {
        "label": "Give a teammate a compliment in character",
        "skill": "Social",
        "done": true
      },
      {
        "label": "Disagree respectfully during a group decision",
        "skill": "Social",
        "done": false
      }
    ]
  },
  {
    "slug": "a-workshop-for-wizards-and-warriors",
    "name": " A Workshop for Wizards and Warriors ",
    "tagline": "The first day of school for new batch of Wizards and Warriors ",
    "tone": "quest-2",
    "group": "Ages 15–18 · ",
    "sessions": "Session 0 ",
    "blurb": "Jubilation fills the air, Students the halls, a new dawn rises on the grounds of The Gillview Institute. Professor Gill Octavius The III viscount of Ardenvale and heir to the throne of Fellmore welcomes you with poise and elegance only someone with a title that long could posses. Join us on an our adventure through the Gillview institute, Will you study with the wizards, train with the barbarians, sing with the bards or forge your own path, Gillview welcomes you to discover what kind of adventurer you really are.",
    "world": [
      {
        "session": "Session 1",
        "title": "First Day Jitters",
        "body": "Our hero's prepare them selves for the exciting day to come, the first step on the way to becoming a real adventurer, The Gillview Institute may be a safe training ground for new adventurers but that doesn't mean there won't be dangers, who knows what really goes on behind those prestigious walls."
      }
    ],
    "characters": [
      {
        "name": "Gill Octavius ",
        "player": "",
        "role": "Professor",
        "note": "Heir to the most powerful kingdom in the land, Gill Octavius in his old age has taken a more ... theoretical approach to adventures, educating the adventurers of a new era, though he never can quite escape a little trouble."
      }
    ],
    "objectives": [
      {
        "label": "Read a short story and retell it",
        "skill": "Reading",
        "done": false
      },
      {
        "label": "Sound out unfamiliar words with support",
        "skill": "Reading",
        "done": false
      },
      {
        "label": "Write a motto or short creative line",
        "skill": "Writing",
        "done": false
      },
      {
        "label": "Write a character backstory paragraph",
        "skill": "Writing",
        "done": false
      },
      {
        "label": "Introduce yourself to a new group",
        "skill": "Social",
        "done": false
      },
      {
        "label": "Ask a quieter player for their idea",
        "skill": "Social",
        "done": false
      }
    ]
  }
];

// Colour tone used for each learning skill badge.
const SKILL_TONE = {
  "Reading": "quest-1",
  "Writing": "quest-5",
  "Social": "quest-3"
};
